[project]
name = "ha-solarman-api"
version = "0.0.1"
description = "Home Assistant custom integration for the Solarman API"
requires-python = ">=3.13.2,<3.14"

[dependency-groups]
dev = [
  "homeassistant>=2025.1",
  "aiohttp>=3",
  "pytest",
  "pytest-asyncio",
  "pytest-homeassistant-custom-component",
  "aioresponses",
  "ruff",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]
